package com.twitterclone.backend.controllers;

import com.twitterclone.backend.model.entities.Role;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Schema(description = "Data Transfer Object for user registration")
public class RegisterRequest {

    @Schema(description = "User's first name", example = "John", requiredMode = Schema.RequiredMode.REQUIRED)
    private String firstname;

    @Schema(description = "User's last name", example = "Doe", requiredMode = Schema.RequiredMode.REQUIRED)
    private String lastname;

    @Schema(description = "User's chosen nickname (must be unique)", example = "johnnyD", requiredMode = Schema.RequiredMode.REQUIRED)
    private String nickname;

    @Schema(description = "User's date of birth", example = "1990-01-15", requiredMode = Schema.RequiredMode.REQUIRED)
    private LocalDate dob;

    @Schema(description = "User's sex/gender (e.g., M, F, O)", example = "M")
    private String sex;

    @Schema(description = "User's email address (must be unique and valid)", example = "john.doe@example.com", requiredMode = Schema.RequiredMode.REQUIRED)
    private String email;

    @Schema(description = "User's chosen password", example = "P@sswOrd123!", requiredMode = Schema.RequiredMode.REQUIRED)
    private String password;

    @Schema(description = "User's phone number (optional)", example = "+11234567890")
    private String phone;

    @Schema(description = "Role assigned to the user. Defaults to USER.", example = "USER")
    @Builder.Default
    private Role role = Role.USER;

    @Schema(description = "URL or path to the user's profile picture (optional)", example = "/uploads/avatars/default.png")
    private String profilePicture;

    @Schema(description = "A short biography of the user (optional)", example = "Loves coding and coffee.")
    private String bio;

    @Schema(description = "Date of account creation (auto-generated by server)", example = "2023-10-27", accessMode = Schema.AccessMode.READ_ONLY)
    @Builder.Default
    private LocalDate creationDate = LocalDate.now();
}