spring:
  application:
    name: backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/twitter_clone}
    username: ${SPRING_DATASOURCE_USERNAME:postgresMaster}
    password: ${SPRING_DATASOURCE_PASSWORD:goPostgresGo}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  main:
    allow-bean-definition-overriding: true
    banner-mode: off

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:b7a002a04fc471eca942e43d9f8974d2826991ccd165dfa0f940df5598704161}
      expiration: ${JWT_EXPIRATION:86400000} # 24 hours default

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.twitterclone.backend: DEBUG

server:
  port: 8080

file:
  upload-dir: ../uploads